name: VIES update

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  get-new-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: soap
          tools: composer:v2

      - name: Get changes
        run: make

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fresh update